// Generated by protod v0.2.1

export class Message {
  constructor() {}

  static fields = {};

  static fromBytes(): Message {
    return new Message();
  }

  static fromJSON(): Message {
    return new Message();
  }

  toBytes(): Uint8Array {
    return Uint8Array.of();
  }

  toJSON() {
    return {};
  }
}
