// Generated by protod v0.1.3
import {
  FieldSet,
  fromBytes,
  fromJSON,
  JSON,
  stringField,
  toBytes,
  toJSON,
} from "../mod.ts";

export enum Importeenum {
  INVALID = 0,
  VALID = 1,
}

export class Importee {
  foo: string;

  constructor(init: Partial<Importee>) {
    this.foo = init.foo ?? "";
  }

  static fields: FieldSet<Importee> = {
    foo: [1, stringField],
  };

  static fromBytes(bytes: Uint8Array): Importee {
    return new Importee(
      fromBytes<Importee>(bytes, Importee.fields),
    );
  }

  static fromJSON(json: JSON): Importee {
    return new Importee(
      fromJSON<Importee>(json, Importee.fields),
    );
  }

  toBytes(): Uint8Array {
    return toBytes<Importee>(this, Importee.fields);
  }

  toJSON() {
    return toJSON<Importee>(this, Importee.fields);
  }
}
